version: '3'

services:
  frontend:
    build: ./frontend
    container_name: docker-course-frontend
    command: serve -s build -l 3000
    restart: unless-stopped

  api:
    build: ./api
    container_name: docker-course-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://docker-course.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: docker-course-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://docker-course.com
      - MONGO_URL=mongodb://api_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: docker-course-api-db
    volumes:
#       - ./database/mongodb/api:/data/db
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: docker-course-auth-db
    volumes:
#       - ./database/mongodb/auth:/data/db
      - mongodb_auth:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: docker-course-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
    mongodb_api:
    mongodb_auth: