version: '3'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    container_name: docker-course-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - docker-course-network

  api:
    build: ./api
    container_name: docker-course-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-course-network

  auth:
    build: ./auth
    container_name: docker-course-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://api_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - docker-course-network

  api_db:
    image: mongo:latest
    container_name: docker-course-api-db
    volumes:
#       - ./database/mongodb/api:/data/db
      - mongodb_api:/data/db
    networks:
      - docker-course-network

  auth_db:
    image: mongo:latest
    container_name: docker-course-auth-db
    volumes:
#       - ./database/mongodb/auth:/data/db
      - mongodb_auth:/data/db
    networks:
      - docker-course-network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-course-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - docker-course-network

volumes:
    mongodb_api:
    mongodb_auth:

networks:
  docker-course-network:
    driver: bridge